version: '3'

services:
  database:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=changeme
    networks:
      - db

  app:
    build:
      context: .
      dockerfile_inline: |
        FROM php:7.2-apache
        RUN docker-php-ext-install pdo pdo_mysql
        RUN docker-php-ext-enable pdo pdo_mysql
    volumes:
      - ./app/src:/var/www/html/
    ports:
      - "8000:80"
    networks:
      - db

networks:
  db:
