services:
  cadvisor:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-web.rule=Host(`monitoring.td.anthonymoll.fr`)"
      - "traefik.http.routers.monitoring-web.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.docker.network=external"
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8080
    

    ports:
      - "8005:8080"
    networks:
      - monitoring
      - external
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M

  nginx:
    image: nginx
    container_name: nginx
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push

networks:
  monitoring:
    driver: bridge
  external:
    external: true
